#!/usr/bin/env python3
"""
NBA Schedule - 2025-25 Season
Official NBA schedule for the complete season.
This is the source of truth for matching API results to games.
"""

def get_nba_schedule():
    """NBA Schedule - 2025-25 Season (Full Season)"""
    nba_schedule = [
        {'match_id': 1, 'round': 1, 'date': 'Tue, Oct 21, 2025 11:30p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Houston Rockets', 'result': '125 - 124'},
        {'match_id': 2, 'round': 1, 'date': 'Wed, Oct 22, 2025 2:00a', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Golden State Warriors', 'result': '109 - 119'},
        {'match_id': 3, 'round': 1, 'date': 'Wed, Oct 22, 2025 11:00p', 'venue': 'Madison Square Garden', 'home_team': 'New York Knicks', 'away_team': 'Cleveland Cavaliers', 'result': '119 - 111'},
        {'match_id': 4, 'round': 1, 'date': 'Wed, Oct 22, 2025 11:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Brooklyn Nets', 'result': '136 - 117'},
        {'match_id': 5, 'round': 1, 'date': 'Wed, Oct 22, 2025 11:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Miami Heat', 'result': '125 - 121'},
        {'match_id': 6, 'round': 1, 'date': 'Wed, Oct 22, 2025 11:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Toronto Raptors', 'result': '118 - 138'},
        {'match_id': 7, 'round': 1, 'date': 'Wed, Oct 22, 2025 11:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Philadelphia 76ers', 'result': '116 - 117'},
        {'match_id': 8, 'round': 1, 'date': 'Thu, Oct 23, 2025 12:00a', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Detroit Pistons', 'result': '115 - 111'},
        {'match_id': 9, 'round': 1, 'date': 'Thu, Oct 23, 2025 12:00a', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'New Orleans Pelicans', 'result': '128 - 122'},
        {'match_id': 10, 'round': 1, 'date': 'Thu, Oct 23, 2025 12:00a', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Washington Wizards', 'result': '133 - 120'},
        {'match_id': 11, 'round': 1, 'date': 'Thu, Oct 23, 2025 1:00a', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'Los Angeles Clippers', 'result': '129 - 108'},
        {'match_id': 12, 'round': 1, 'date': 'Thu, Oct 23, 2025 1:30a', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'San Antonio Spurs', 'result': '92 - 125'},
        {'match_id': 13, 'round': 1, 'date': 'Thu, Oct 23, 2025 2:00a', 'venue': 'Mortgage Matchup Center', 'home_team': 'Phoenix Suns', 'away_team': 'Sacramento Kings', 'result': '120 - 116'},
        {'match_id': 14, 'round': 1, 'date': 'Thu, Oct 23, 2025 2:00a', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Minnesota Timberwolves', 'result': '114 - 118'},
        {'match_id': 15, 'round': 1, 'date': 'Thu, Oct 23, 2025 11:30p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Oklahoma City Thunder', 'result': '135 - 141'},
        {'match_id': 16, 'round': 1, 'date': 'Fri, Oct 24, 2025 2:00a', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Denver Nuggets', 'result': '137 - 131'},
        {'match_id': 17, 'round': 1, 'date': 'Fri, Oct 24, 2025 10:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Milwaukee Bucks', 'result': '116 - 122'},
        {'match_id': 18, 'round': 1, 'date': 'Fri, Oct 24, 2025 11:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Atlanta Hawks', 'result': '107 - 111'},
        {'match_id': 19, 'round': 1, 'date': 'Fri, Oct 24, 2025 11:30p', 'venue': 'Madison Square Garden', 'home_team': 'New York Knicks', 'away_team': 'Boston Celtics', 'result': '105 - 95'},
        {'match_id': 20, 'round': 1, 'date': 'Fri, Oct 24, 2025 11:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Cleveland Cavaliers', 'result': '124 - 131'},
        {'match_id': 21, 'round': 1, 'date': 'Sat, Oct 25, 2025 12:00a', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Detroit Pistons', 'result': '111 - 115'},
        {'match_id': 22, 'round': 1, 'date': 'Sat, Oct 25, 2025 12:00a', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Miami Heat', 'result': '114 - 146'},
        {'match_id': 23, 'round': 1, 'date': 'Sat, Oct 25, 2025 12:00a', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'San Antonio Spurs', 'result': '116 - 120'},
        {'match_id': 24, 'round': 1, 'date': 'Sat, Oct 25, 2025 12:30a', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Washington Wizards', 'result': '107 - 117'},
        {'match_id': 25, 'round': 1, 'date': 'Sat, Oct 25, 2025 2:00a', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Minnesota Timberwolves', 'result': '128 - 110'},
        {'match_id': 26, 'round': 1, 'date': 'Sat, Oct 25, 2025 2:00a', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Golden State Warriors', 'result': '139 - 119'},
        {'match_id': 27, 'round': 1, 'date': 'Sat, Oct 25, 2025 2:00a', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Utah Jazz', 'result': '105 - 104'},
        {'match_id': 28, 'round': 1, 'date': 'Sat, Oct 25, 2025 2:30a', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Phoenix Suns', 'result': '129 - 102'},
        {'match_id': 29, 'round': 1, 'date': 'Sat, Oct 25, 2025 11:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Chicago Bulls', 'result': '98 - 110'},
        {'match_id': 30, 'round': 1, 'date': 'Sat, Oct 25, 2025 11:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Oklahoma City Thunder', 'result': '100 - 117'},
        {'match_id': 31, 'round': 1, 'date': 'Sat, Oct 25, 2025 11:30p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Charlotte Hornets', 'result': '125 - 121'},
        {'match_id': 32, 'round': 1, 'date': 'Sun, Oct 26, 2025 12:00a', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Indiana Pacers', 'result': '128 - 103'},
        {'match_id': 33, 'round': 1, 'date': 'Sun, Oct 26, 2025 1:00a', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Phoenix Suns', 'result': '133 - 111'},
        {'match_id': 34, 'round': 1, 'date': 'Sun, Oct 26, 2025 6:00p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Brooklyn Nets', 'result': '118 - 107'},
        {'match_id': 35, 'round': 1, 'date': 'Sun, Oct 26, 2025 7:30p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Boston Celtics', 'result': '119 - 113'},
        {'match_id': 36, 'round': 1, 'date': 'Sun, Oct 26, 2025 10:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Milwaukee Bucks', 'result': '118 - 113'},
        {'match_id': 37, 'round': 1, 'date': 'Sun, Oct 26, 2025 10:00p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'New York Knicks', 'result': '115 - 107'},
        {'match_id': 38, 'round': 1, 'date': 'Sun, Oct 26, 2025 10:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Charlotte Hornets', 'result': '113 - 139'},
        {'match_id': 39, 'round': 1, 'date': 'Sun, Oct 26, 2025 11:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Indiana Pacers', 'result': '114 - 110'},
        {'match_id': 40, 'round': 1, 'date': 'Sun, Oct 26, 2025 11:30p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Toronto Raptors', 'result': '139 - 129'},
        {'match_id': 41, 'round': 1, 'date': 'Mon, Oct 27, 2025 1:00a', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Portland Trail Blazers', 'result': '114 - 107'},
        {'match_id': 42, 'round': 1, 'date': 'Mon, Oct 27, 2025 1:00a', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Los Angeles Lakers', 'result': '120 - 127'},
        {'match_id': 43, 'round': 1, 'date': 'Mon, Oct 27, 2025 11:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Cleveland Cavaliers', 'result': '95 - 116'},
        {'match_id': 44, 'round': 1, 'date': 'Mon, Oct 27, 2025 11:00p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Orlando Magic', 'result': '136 - 124'},
        {'match_id': 45, 'round': 1, 'date': 'Tue, Oct 28, 2025 12:00a', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Atlanta Hawks', 'result': '128 - 123'},
        {'match_id': 46, 'round': 1, 'date': 'Tue, Oct 28, 2025 12:00a', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Brooklyn Nets', 'result': '137 - 109'},
        {'match_id': 47, 'round': 1, 'date': 'Tue, Oct 28, 2025 12:00a', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Boston Celtics', 'result': '90 - 122'},
        {'match_id': 48, 'round': 1, 'date': 'Tue, Oct 28, 2025 12:00a', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Toronto Raptors', 'result': '121 - 103'},
        {'match_id': 49, 'round': 1, 'date': 'Tue, Oct 28, 2025 12:30a', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Oklahoma City Thunder', 'result': '94 - 101'},
        {'match_id': 50, 'round': 1, 'date': 'Tue, Oct 28, 2025 1:00a', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'Phoenix Suns', 'result': '138 - 134'},
        {'match_id': 51, 'round': 1, 'date': 'Tue, Oct 28, 2025 1:30a', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Denver Nuggets', 'result': '114 - 127'},
        {'match_id': 52, 'round': 1, 'date': 'Tue, Oct 28, 2025 2:00a', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Memphis Grizzlies', 'result': '131 - 118'},
        {'match_id': 53, 'round': 1, 'date': 'Tue, Oct 28, 2025 2:30a', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Portland Trail Blazers', 'result': '108 - 122'},
        {'match_id': 54, 'round': 54, 'date': 'Tue, Oct 28, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 55, 'round': 55, 'date': 'Tue, Oct 28, 2025 7:30p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 56, 'round': 56, 'date': 'Tue, Oct 28, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 57, 'round': 57, 'date': 'Tue, Oct 28, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 58, 'round': 58, 'date': 'Tue, Oct 28, 2025 11:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 59, 'round': 59, 'date': 'Wed, Oct 29, 2025 7:00p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 60, 'round': 60, 'date': 'Wed, Oct 29, 2025 7:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 61, 'round': 61, 'date': 'Wed, Oct 29, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 62, 'round': 62, 'date': 'Wed, Oct 29, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 63, 'round': 63, 'date': 'Wed, Oct 29, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 64, 'round': 64, 'date': 'Wed, Oct 29, 2025 8:30p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 65, 'round': 65, 'date': 'Wed, Oct 29, 2025 9:00p', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 66, 'round': 66, 'date': 'Wed, Oct 29, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 67, 'round': 67, 'date': 'Wed, Oct 29, 2025 9:30p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 68, 'round': 68, 'date': 'Wed, Oct 29, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 69, 'round': 69, 'date': 'Thu, Oct 30, 2025 7:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 70, 'round': 70, 'date': 'Thu, Oct 30, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 71, 'round': 71, 'date': 'Thu, Oct 30, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 72, 'round': 72, 'date': 'Thu, Oct 30, 2025 8:30p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 73, 'round': 73, 'date': 'Fri, Oct 31, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 74, 'round': 74, 'date': 'Fri, Oct 31, 2025 7:00p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 75, 'round': 75, 'date': 'Fri, Oct 31, 2025 7:30p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Toronto Raptors', 'result': ''},
        {'match_id': 76, 'round': 76, 'date': 'Fri, Oct 31, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 77, 'round': 77, 'date': 'Fri, Oct 31, 2025 9:30p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 78, 'round': 78, 'date': 'Fri, Oct 31, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 79, 'round': 79, 'date': 'Fri, Oct 31, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 80, 'round': 80, 'date': 'Fri, Oct 31, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 81, 'round': 81, 'date': 'Sat, Nov 1, 2025 5:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 82, 'round': 82, 'date': 'Sat, Nov 1, 2025 6:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 83, 'round': 83, 'date': 'Sat, Nov 1, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 84, 'round': 84, 'date': 'Sat, Nov 1, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 85, 'round': 85, 'date': 'Sat, Nov 1, 2025 8:00p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 86, 'round': 86, 'date': 'Sat, Nov 1, 2025 10:00p', 'venue': 'Mexico City Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 87, 'round': 87, 'date': 'Sun, Nov 2, 2025 3:30p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 88, 'round': 88, 'date': 'Sun, Nov 2, 2025 6:00p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 89, 'round': 89, 'date': 'Sun, Nov 2, 2025 6:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 90, 'round': 90, 'date': 'Sun, Nov 2, 2025 6:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 91, 'round': 91, 'date': 'Sun, Nov 2, 2025 6:00p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 92, 'round': 92, 'date': 'Sun, Nov 2, 2025 7:00p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 93, 'round': 93, 'date': 'Sun, Nov 2, 2025 8:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'San Antonio Spurs', 'result': ''},
        {'match_id': 94, 'round': 94, 'date': 'Sun, Nov 2, 2025 9:30p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 95, 'round': 95, 'date': 'Mon, Nov 3, 2025 7:00p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 96, 'round': 96, 'date': 'Mon, Nov 3, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 97, 'round': 97, 'date': 'Mon, Nov 3, 2025 7:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 98, 'round': 98, 'date': 'Mon, Nov 3, 2025 7:30p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 99, 'round': 99, 'date': 'Mon, Nov 3, 2025 8:00p', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 100, 'round': 100, 'date': 'Mon, Nov 3, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 101, 'round': 101, 'date': 'Mon, Nov 3, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 102, 'round': 102, 'date': 'Mon, Nov 3, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 103, 'round': 103, 'date': 'Mon, Nov 3, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 104, 'round': 104, 'date': 'Tue, Nov 4, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 105, 'round': 105, 'date': 'Tue, Nov 4, 2025 8:00p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 106, 'round': 106, 'date': 'Tue, Nov 4, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 107, 'round': 107, 'date': 'Tue, Nov 4, 2025 8:00p', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 108, 'round': 108, 'date': 'Tue, Nov 4, 2025 10:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 109, 'round': 109, 'date': 'Tue, Nov 4, 2025 11:00p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 110, 'round': 110, 'date': 'Wed, Nov 5, 2025 7:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 112, 'round': 112, 'date': 'Wed, Nov 5, 2025 7:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 113, 'round': 113, 'date': 'Wed, Nov 5, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Brooklyn Nets', 'result': ''},
        {'match_id': 114, 'round': 114, 'date': 'Wed, Nov 5, 2025 7:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 115, 'round': 115, 'date': 'Wed, Nov 5, 2025 7:30p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 116, 'round': 116, 'date': 'Wed, Nov 5, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 117, 'round': 117, 'date': 'Wed, Nov 5, 2025 8:30p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 118, 'round': 118, 'date': 'Wed, Nov 5, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 119, 'round': 119, 'date': 'Wed, Nov 5, 2025 10:00p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'San Antonio Spurs', 'result': ''},
        {'match_id': 120, 'round': 120, 'date': 'Wed, Nov 5, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 121, 'round': 121, 'date': 'Wed, Nov 5, 2025 10:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 122, 'round': 122, 'date': 'Thu, Nov 6, 2025 9:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 123, 'round': 123, 'date': 'Fri, Nov 7, 2025 7:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 124, 'round': 124, 'date': 'Fri, Nov 7, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 125, 'round': 125, 'date': 'Fri, Nov 7, 2025 7:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Toronto Raptors', 'result': ''},
        {'match_id': 126, 'round': 126, 'date': 'Fri, Nov 7, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 127, 'round': 127, 'date': 'Fri, Nov 7, 2025 7:30p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 128, 'round': 128, 'date': 'Fri, Nov 7, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 129, 'round': 129, 'date': 'Fri, Nov 7, 2025 8:00p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 130, 'round': 130, 'date': 'Fri, Nov 7, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 131, 'round': 131, 'date': 'Fri, Nov 7, 2025 8:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 132, 'round': 132, 'date': 'Fri, Nov 7, 2025 10:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 133, 'round': 133, 'date': 'Fri, Nov 7, 2025 10:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Oklahoma City Thunder', 'result': ''},
    ]
    return nba_schedule
