def get_nba_schedule():
    """NBA Schedule - 2025-2026 Season (Partial)"""
    nba_schedule = [
        {'match_id': 1, 'round': 1, 'date': 'Tue, Oct 21, 2025 11:30p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Houston Rockets', 'result': '125-124'},
        {'match_id': 2, 'round': 2, 'date': 'Wed, Oct 22, 2025 2:00a', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Golden State Warriors', 'result': '109-119'},
        {'match_id': 3, 'round': 3, 'date': 'Wed, Oct 22, 2025 11:00p', 'venue': 'Madison Square Garden', 'home_team': 'New York Knicks', 'away_team': 'Cleveland Cavaliers', 'result': '119-111'},
        {'match_id': 4, 'round': 4, 'date': 'Wed, Oct 22, 2025 11:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Brooklyn Nets', 'result': '136-117'},
        {'match_id': 5, 'round': 5, 'date': 'Wed, Oct 22, 2025 11:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Miami Heat', 'result': '125-121'},
        {'match_id': 6, 'round': 6, 'date': 'Wed, Oct 22, 2025 11:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Toronto Raptors', 'result': '118-138'},
        {'match_id': 7, 'round': 7, 'date': 'Wed, Oct 22, 2025 11:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Philadelphia 76ers', 'result': '116-117'},
        {'match_id': 8, 'round': 8, 'date': 'Thu, Oct 23, 2025 12:00a', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Detroit Pistons', 'result': '115-111'},
        {'match_id': 9, 'round': 9, 'date': 'Thu, Oct 23, 2025 12:00a', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'New Orleans Pelicans', 'result': '128-122'},
        {'match_id': 10, 'round': 10, 'date': 'Thu, Oct 23, 2025 12:00a', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Washington Wizards', 'result': '133-120'},
        {'match_id': 11, 'round': 11, 'date': 'Thu, Oct 23, 2025 1:00a', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'Los Angeles Clippers', 'result': '129-108'},
        {'match_id': 12, 'round': 12, 'date': 'Thu, Oct 23, 2025 1:30a', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'San Antonio Spurs', 'result': '92-125'},
        {'match_id': 13, 'round': 13, 'date': 'Thu, Oct 23, 2025 2:00a', 'venue': 'Mortgage Matchup Center', 'home_team': 'Phoenix Suns', 'away_team': 'Sacramento Kings', 'result': '120-116'},
        {'match_id': 14, 'round': 14, 'date': 'Thu, Oct 23, 2025 2:00a', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Minnesota Timberwolves', 'result': '114-118'},
        {'match_id': 15, 'round': 15, 'date': 'Thu, Oct 23, 2025 11:30p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Oklahoma City Thunder', 'result': '135-141'},
        {'match_id': 16, 'round': 16, 'date': 'Fri, Oct 24, 2025 2:00a', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Denver Nuggets', 'result': '137-131'},
        {'match_id': 17, 'round': 17, 'date': 'Fri, Oct 24, 2025 10:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Milwaukee Bucks', 'result': '116-122'},
        {'match_id': 18, 'round': 18, 'date': 'Fri, Oct 24, 2025 11:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Atlanta Hawks', 'result': '107-111'},
        {'match_id': 19, 'round': 19, 'date': 'Fri, Oct 24, 2025 11:30p', 'venue': 'Madison Square Garden', 'home_team': 'New York Knicks', 'away_team': 'Boston Celtics', 'result': '105-95'},
        {'match_id': 20, 'round': 20, 'date': 'Fri, Oct 24, 2025 11:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Cleveland Cavaliers', 'result': '124-131'},
        {'match_id': 21, 'round': 21, 'date': 'Sat, Oct 25, 2025 12:00a', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Detroit Pistons', 'result': '111-115'},
        {'match_id': 22, 'round': 22, 'date': 'Sat, Oct 25, 2025 12:00a', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Miami Heat', 'result': '114-146'},
        {'match_id': 23, 'round': 23, 'date': 'Sat, Oct 25, 2025 12:00a', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'San Antonio Spurs', 'result': '116-120'},
        {'match_id': 24, 'round': 24, 'date': 'Sat, Oct 25, 2025 12:30a', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Washington Wizards', 'result': '107-117'},
        {'match_id': 25, 'round': 25, 'date': 'Sat, Oct 25, 2025 2:00a', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Minnesota Timberwolves', 'result': '128-110'},
        {'match_id': 26, 'round': 26, 'date': 'Sat, Oct 25, 2025 2:00a', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Golden State Warriors', 'result': '139-119'},
        {'match_id': 27, 'round': 27, 'date': 'Sat, Oct 25, 2025 2:00a', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Utah Jazz', 'result': '105-104'},
        {'match_id': 28, 'round': 28, 'date': 'Sat, Oct 25, 2025 2:30a', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Phoenix Suns', 'result': '129-102'},
        {'match_id': 29, 'round': 29, 'date': 'Sat, Oct 25, 2025 11:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Chicago Bulls', 'result': '98-110'},
        {'match_id': 30, 'round': 30, 'date': 'Sat, Oct 25, 2025 11:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Oklahoma City Thunder', 'result': '100-117'},
        {'match_id': 31, 'round': 31, 'date': 'Sat, Oct 25, 2025 11:30p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Charlotte Hornets', 'result': '125-121'},
        {'match_id': 32, 'round': 32, 'date': 'Sun, Oct 26, 2025 12:00a', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Indiana Pacers', 'result': '128-103'},
        {'match_id': 33, 'round': 33, 'date': 'Sun, Oct 26, 2025 1:00a', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Phoenix Suns', 'result': '133-111'},
        {'match_id': 34, 'round': 34, 'date': 'Sun, Oct 26, 2025 6:00p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Brooklyn Nets', 'result': '118-107'},
        {'match_id': 35, 'round': 35, 'date': 'Sun, Oct 26, 2025 7:30p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Boston Celtics', 'result': '119-113'},
        {'match_id': 36, 'round': 36, 'date': 'Sun, Oct 26, 2025 10:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Milwaukee Bucks', 'result': '118-113'},
        {'match_id': 37, 'round': 37, 'date': 'Sun, Oct 26, 2025 10:00p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'New York Knicks', 'result': '115-107'},
        {'match_id': 38, 'round': 38, 'date': 'Sun, Oct 26, 2025 10:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Charlotte Hornets', 'result': '113-139'},
        {'match_id': 39, 'round': 39, 'date': 'Sun, Oct 26, 2025 11:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Indiana Pacers', 'result': '114-110'},
        {'match_id': 40, 'round': 40, 'date': 'Sun, Oct 26, 2025 11:30p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Toronto Raptors', 'result': '139-129'},
        {'match_id': 41, 'round': 41, 'date': 'Mon, Oct 27, 2025 1:00a', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Portland Trail Blazers', 'result': '114-107'},
        {'match_id': 42, 'round': 42, 'date': 'Mon, Oct 27, 2025 1:00a', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Los Angeles Lakers', 'result': '120-127'},
        {'match_id': 43, 'round': 43, 'date': 'Mon, Oct 27, 2025 11:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Cleveland Cavaliers', 'result': '95-116'},
        {'match_id': 44, 'round': 44, 'date': 'Mon, Oct 27, 2025 11:00p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Orlando Magic', 'result': '136-124'},
        {'match_id': 45, 'round': 45, 'date': 'Tue, Oct 28, 2025 12:00a', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Atlanta Hawks', 'result': '128-123'},
        {'match_id': 46, 'round': 46, 'date': 'Tue, Oct 28, 2025 12:00a', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Brooklyn Nets', 'result': '137-109'},
        {'match_id': 47, 'round': 47, 'date': 'Tue, Oct 28, 2025 12:00a', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Boston Celtics', 'result': '90-122'},
        {'match_id': 48, 'round': 48, 'date': 'Tue, Oct 28, 2025 12:00a', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Toronto Raptors', 'result': '121-103'},
        {'match_id': 49, 'round': 49, 'date': 'Tue, Oct 28, 2025 12:30a', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Oklahoma City Thunder', 'result': '94-101'},
        {'match_id': 50, 'round': 50, 'date': 'Tue, Oct 28, 2025 1:00a', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'Phoenix Suns', 'result': '138-134'},
        {'match_id': 51, 'round': 51, 'date': 'Tue, Oct 28, 2025 1:30a', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Denver Nuggets', 'result': '114-127'},
        {'match_id': 52, 'round': 52, 'date': 'Tue, Oct 28, 2025 2:00a', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Memphis Grizzlies', 'result': '131-118'},
        {'match_id': 53, 'round': 53, 'date': 'Tue, Oct 28, 2025 2:30a', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Portland Trail Blazers', 'result': '108-122'},
        {'match_id': 54, 'round': 54, 'date': 'Tue, Oct 28, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 55, 'round': 55, 'date': 'Tue, Oct 28, 2025 7:30p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 56, 'round': 56, 'date': 'Tue, Oct 28, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 57, 'round': 57, 'date': 'Tue, Oct 28, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 58, 'round': 58, 'date': 'Tue, Oct 28, 2025 11:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 59, 'round': 59, 'date': 'Wed, Oct 29, 2025 7:00p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 60, 'round': 60, 'date': 'Wed, Oct 29, 2025 7:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 61, 'round': 61, 'date': 'Wed, Oct 29, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 62, 'round': 62, 'date': 'Wed, Oct 29, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 63, 'round': 63, 'date': 'Wed, Oct 29, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 64, 'round': 64, 'date': 'Wed, Oct 29, 2025 8:30p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 65, 'round': 65, 'date': 'Wed, Oct 29, 2025 9:00p', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 66, 'round': 66, 'date': 'Wed, Oct 29, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 67, 'round': 67, 'date': 'Wed, Oct 29, 2025 9:30p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 68, 'round': 68, 'date': 'Wed, Oct 29, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 69, 'round': 69, 'date': 'Thu, Oct 30, 2025 7:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 70, 'round': 70, 'date': 'Thu, Oct 30, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 71, 'round': 71, 'date': 'Thu, Oct 30, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 72, 'round': 72, 'date': 'Thu, Oct 30, 2025 8:30p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 73, 'round': 73, 'date': 'Fri, Oct 31, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 74, 'round': 74, 'date': 'Fri, Oct 31, 2025 7:00p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 75, 'round': 75, 'date': 'Fri, Oct 31, 2025 7:30p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Toronto Raptors', 'result': ''},
        {'match_id': 76, 'round': 76, 'date': 'Fri, Oct 31, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 77, 'round': 77, 'date': 'Fri, Oct 31, 2025 9:30p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 78, 'round': 78, 'date': 'Fri, Oct 31, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 79, 'round': 79, 'date': 'Fri, Oct 31, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 80, 'round': 80, 'date': 'Fri, Oct 31, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 81, 'round': 81, 'date': 'Sat, Nov 1, 2025 5:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 82, 'round': 82, 'date': 'Sat, Nov 1, 2025 6:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 83, 'round': 83, 'date': 'Sat, Nov 1, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 84, 'round': 84, 'date': 'Sat, Nov 1, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 85, 'round': 85, 'date': 'Sat, Nov 1, 2025 8:00p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 86, 'round': 86, 'date': 'Sat, Nov 1, 2025 10:00p', 'venue': 'Mexico City Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 87, 'round': 87, 'date': 'Sun, Nov 2, 2025 3:30p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 88, 'round': 88, 'date': 'Sun, Nov 2, 2025 6:00p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 89, 'round': 89, 'date': 'Sun, Nov 2, 2025 6:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 90, 'round': 90, 'date': 'Sun, Nov 2, 2025 6:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 91, 'round': 91, 'date': 'Sun, Nov 2, 2025 6:00p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 92, 'round': 92, 'date': 'Sun, Nov 2, 2025 7:00p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 93, 'round': 93, 'date': 'Sun, Nov 2, 2025 8:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'San Antonio Spurs', 'result': ''},
        {'match_id': 94, 'round': 94, 'date': 'Sun, Nov 2, 2025 9:30p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 95, 'round': 95, 'date': 'Mon, Nov 3, 2025 7:00p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 96, 'round': 96, 'date': 'Mon, Nov 3, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 97, 'round': 97, 'date': 'Mon, Nov 3, 2025 7:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 98, 'round': 98, 'date': 'Mon, Nov 3, 2025 7:30p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 99, 'round': 99, 'date': 'Mon, Nov 3, 2025 8:00p', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 100, 'round': 100, 'date': 'Mon, Nov 3, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 101, 'round': 101, 'date': 'Mon, Nov 3, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 102, 'round': 102, 'date': 'Mon, Nov 3, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 103, 'round': 103, 'date': 'Mon, Nov 3, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 104, 'round': 104, 'date': 'Tue, Nov 4, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 105, 'round': 105, 'date': 'Tue, Nov 4, 2025 8:00p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 106, 'round': 106, 'date': 'Tue, Nov 4, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 107, 'round': 107, 'date': 'Tue, Nov 4, 2025 8:00p', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 108, 'round': 108, 'date': 'Tue, Nov 4, 2025 10:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 109, 'round': 109, 'date': 'Tue, Nov 4, 2025 11:00p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 110, 'round': 110, 'date': 'Wed, Nov 5, 2025 7:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 112, 'round': 112, 'date': 'Wed, Nov 5, 2025 7:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 113, 'round': 113, 'date': 'Wed, Nov 5, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Brooklyn Nets', 'result': ''},
        {'match_id': 114, 'round': 114, 'date': 'Wed, Nov 5, 2025 7:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 115, 'round': 115, 'date': 'Wed, Nov 5, 2025 7:30p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 116, 'round': 116, 'date': 'Wed, Nov 5, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 117, 'round': 117, 'date': 'Wed, Nov 5, 2025 8:30p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 118, 'round': 118, 'date': 'Wed, Nov 5, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 119, 'round': 119, 'date': 'Wed, Nov 5, 2025 10:00p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'San Antonio Spurs', 'result': ''},
        {'match_id': 120, 'round': 120, 'date': 'Wed, Nov 5, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 121, 'round': 121, 'date': 'Wed, Nov 5, 2025 10:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 122, 'round': 122, 'date': 'Thu, Nov 6, 2025 9:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 123, 'round': 123, 'date': 'Fri, Nov 7, 2025 7:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 124, 'round': 124, 'date': 'Fri, Nov 7, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 125, 'round': 125, 'date': 'Fri, Nov 7, 2025 7:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Toronto Raptors', 'result': ''},
        {'match_id': 126, 'round': 126, 'date': 'Fri, Nov 7, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 127, 'round': 127, 'date': 'Fri, Nov 7, 2025 7:30p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 128, 'round': 128, 'date': 'Fri, Nov 7, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 129, 'round': 129, 'date': 'Fri, Nov 7, 2025 8:00p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 130, 'round': 130, 'date': 'Fri, Nov 7, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 131, 'round': 131, 'date': 'Fri, Nov 7, 2025 8:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 132, 'round': 132, 'date': 'Fri, Nov 7, 2025 10:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 133, 'round': 133, 'date': 'Fri, Nov 7, 2025 10:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 134, 'round': 134, 'date': 'Sat, Nov 8, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 135, 'round': 135, 'date': 'Sat, Nov 8, 2025 7:30p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Toronto Raptors', 'result': ''},
        {'match_id': 136, 'round': 136, 'date': 'Sat, Nov 8, 2025 8:00p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 137, 'round': 137, 'date': 'Sat, Nov 8, 2025 8:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 138, 'round': 138, 'date': 'Sat, Nov 8, 2025 8:00p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 139, 'round': 139, 'date': 'Sat, Nov 8, 2025 8:00p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 140, 'round': 140, 'date': 'Sat, Nov 8, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 141, 'round': 141, 'date': 'Sat, Nov 8, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 143, 'round': 143, 'date': 'Sun, Nov 9, 2025 3:30p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 144, 'round': 144, 'date': 'Sun, Nov 9, 2025 6:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 145, 'round': 145, 'date': 'Sun, Nov 9, 2025 6:00p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Brooklyn Nets', 'result': ''},
        {'match_id': 146, 'round': 146, 'date': 'Sun, Nov 9, 2025 6:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 147, 'round': 147, 'date': 'Sun, Nov 9, 2025 7:30p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 148, 'round': 148, 'date': 'Sun, Nov 9, 2025 8:30p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 149, 'round': 149, 'date': 'Sun, Nov 9, 2025 9:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 150, 'round': 150, 'date': 'Mon, Nov 10, 2025 7:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 151, 'round': 151, 'date': 'Mon, Nov 10, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 152, 'round': 152, 'date': 'Mon, Nov 10, 2025 8:00p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 153, 'round': 153, 'date': 'Mon, Nov 10, 2025 8:00p', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 154, 'round': 154, 'date': 'Mon, Nov 10, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 155, 'round': 155, 'date': 'Mon, Nov 10, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 156, 'round': 156, 'date': 'Mon, Nov 10, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 157, 'round': 157, 'date': 'Tue, Nov 11, 2025 7:00p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 158, 'round': 158, 'date': 'Tue, Nov 11, 2025 7:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 159, 'round': 159, 'date': 'Tue, Nov 11, 2025 7:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 160, 'round': 160, 'date': 'Tue, Nov 11, 2025 7:30p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 161, 'round': 161, 'date': 'Tue, Nov 11, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'San Antonio Spurs', 'result': ''},
        {'match_id': 162, 'round': 162, 'date': 'Tue, Nov 11, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 163, 'round': 163, 'date': 'Tue, Nov 11, 2025 10:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 164, 'round': 164, 'date': 'Tue, Nov 11, 2025 10:00p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 165, 'round': 165, 'date': 'Wed, Nov 12, 2025 7:00p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 166, 'round': 166, 'date': 'Wed, Nov 12, 2025 7:00p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 167, 'round': 167, 'date': 'Wed, Nov 12, 2025 7:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 168, 'round': 168, 'date': 'Wed, Nov 12, 2025 8:00p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 169, 'round': 169, 'date': 'Wed, Nov 12, 2025 9:00p', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 170, 'round': 170, 'date': 'Wed, Nov 12, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 171, 'round': 171, 'date': 'Thu, Nov 13, 2025 7:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 172, 'round': 172, 'date': 'Thu, Nov 13, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 173, 'round': 173, 'date': 'Thu, Nov 13, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 174, 'round': 174, 'date': 'Thu, Nov 13, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 175, 'round': 175, 'date': 'Thu, Nov 13, 2025 7:30p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 176, 'round': 176, 'date': 'Thu, Nov 13, 2025 8:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 177, 'round': 177, 'date': 'Thu, Nov 13, 2025 8:00p', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 178, 'round': 178, 'date': 'Thu, Nov 13, 2025 8:30p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 179, 'round': 179, 'date': 'Thu, Nov 13, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 180, 'round': 180, 'date': 'Thu, Nov 13, 2025 10:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 181, 'round': 181, 'date': 'Fri, Nov 14, 2025 7:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 182, 'round': 182, 'date': 'Fri, Nov 14, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 183, 'round': 183, 'date': 'Fri, Nov 14, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 184, 'round': 184, 'date': 'Fri, Nov 14, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 185, 'round': 185, 'date': 'Fri, Nov 14, 2025 8:30p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 186, 'round': 186, 'date': 'Fri, Nov 14, 2025 10:00p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 187, 'round': 187, 'date': 'Fri, Nov 14, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 188, 'round': 188, 'date': 'Sat, Nov 15, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 189, 'round': 189, 'date': 'Sat, Nov 15, 2025 7:30p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 190, 'round': 190, 'date': 'Sat, Nov 15, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 191, 'round': 191, 'date': 'Sat, Nov 15, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 192, 'round': 192, 'date': 'Sat, Nov 15, 2025 8:00p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 193, 'round': 193, 'date': 'Sat, Nov 15, 2025 8:00p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 194, 'round': 194, 'date': 'Sat, Nov 15, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 195, 'round': 195, 'date': 'Sun, Nov 16, 2025 3:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Brooklyn Nets', 'result': ''},
        {'match_id': 196, 'round': 196, 'date': 'Sun, Nov 16, 2025 5:00p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 197, 'round': 197, 'date': 'Sun, Nov 16, 2025 6:00p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 198, 'round': 198, 'date': 'Sun, Nov 16, 2025 6:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 199, 'round': 199, 'date': 'Sun, Nov 16, 2025 6:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 200, 'round': 200, 'date': 'Sun, Nov 16, 2025 6:00p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 201, 'round': 201, 'date': 'Sun, Nov 16, 2025 7:00p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 202, 'round': 202, 'date': 'Sun, Nov 16, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 203, 'round': 203, 'date': 'Sun, Nov 16, 2025 9:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 204, 'round': 204, 'date': 'Mon, Nov 17, 2025 7:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 205, 'round': 205, 'date': 'Mon, Nov 17, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 206, 'round': 206, 'date': 'Mon, Nov 17, 2025 7:30p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 207, 'round': 207, 'date': 'Mon, Nov 17, 2025 8:00p', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 208, 'round': 208, 'date': 'Mon, Nov 17, 2025 8:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 209, 'round': 209, 'date': 'Mon, Nov 17, 2025 9:00p', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 210, 'round': 210, 'date': 'Mon, Nov 17, 2025 10:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 211, 'round': 211, 'date': 'Mon, Nov 17, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 212, 'round': 212, 'date': 'Tue, Nov 18, 2025 7:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 213, 'round': 213, 'date': 'Tue, Nov 18, 2025 7:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 214, 'round': 214, 'date': 'Tue, Nov 18, 2025 7:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 215, 'round': 215, 'date': 'Tue, Nov 18, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 216, 'round': 216, 'date': 'Tue, Nov 18, 2025 7:30p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Brooklyn Nets', 'result': ''},
        {'match_id': 217, 'round': 217, 'date': 'Tue, Nov 18, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 218, 'round': 218, 'date': 'Tue, Nov 18, 2025 8:00p', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 219, 'round': 219, 'date': 'Tue, Nov 18, 2025 8:30p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 220, 'round': 220, 'date': 'Tue, Nov 18, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 221, 'round': 221, 'date': 'Tue, Nov 18, 2025 10:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 222, 'round': 222, 'date': 'Tue, Nov 18, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 223, 'round': 223, 'date': 'Wed, Nov 19, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 224, 'round': 224, 'date': 'Wed, Nov 19, 2025 7:00p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 225, 'round': 225, 'date': 'Wed, Nov 19, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 226, 'round': 226, 'date': 'Wed, Nov 19, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 227, 'round': 227, 'date': 'Wed, Nov 19, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 228, 'round': 228, 'date': 'Wed, Nov 19, 2025 8:00p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 229, 'round': 229, 'date': 'Wed, Nov 19, 2025 10:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 230, 'round': 230, 'date': 'Wed, Nov 19, 2025 10:00p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 231, 'round': 231, 'date': 'Wed, Nov 19, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 232, 'round': 232, 'date': 'Thu, Nov 20, 2025 8:00p', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 233, 'round': 233, 'date': 'Fri, Nov 21, 2025 7:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 234, 'round': 234, 'date': 'Fri, Nov 21, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 235, 'round': 235, 'date': 'Fri, Nov 21, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 236, 'round': 236, 'date': 'Fri, Nov 21, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 237, 'round': 237, 'date': 'Fri, Nov 21, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 238, 'round': 238, 'date': 'Fri, Nov 21, 2025 8:00p', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 239, 'round': 239, 'date': 'Fri, Nov 21, 2025 8:00p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 240, 'round': 240, 'date': 'Fri, Nov 21, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 241, 'round': 241, 'date': 'Fri, Nov 21, 2025 8:30p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 242, 'round': 242, 'date': 'Fri, Nov 21, 2025 9:00p', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'San Antonio Spurs', 'result': ''},
        {'match_id': 243, 'round': 243, 'date': 'Fri, Nov 21, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 244, 'round': 244, 'date': 'Fri, Nov 21, 2025 10:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 245, 'round': 245, 'date': 'Sat, Nov 22, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Brooklyn Nets', 'result': ''},
        {'match_id': 246, 'round': 246, 'date': 'Sat, Nov 22, 2025 7:30p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 247, 'round': 247, 'date': 'Sat, Nov 22, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 248, 'round': 248, 'date': 'Sat, Nov 22, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 249, 'round': 249, 'date': 'Sat, Nov 22, 2025 10:00p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 250, 'round': 250, 'date': 'Sun, Nov 23, 2025 3:30p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 251, 'round': 251, 'date': 'Sun, Nov 23, 2025 6:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 252, 'round': 252, 'date': 'Sun, Nov 23, 2025 6:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 253, 'round': 253, 'date': 'Sun, Nov 23, 2025 6:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Toronto Raptors', 'result': ''},
        {'match_id': 254, 'round': 254, 'date': 'Sun, Nov 23, 2025 6:00p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 255, 'round': 255, 'date': 'Sun, Nov 23, 2025 7:00p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 256, 'round': 256, 'date': 'Sun, Nov 23, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 257, 'round': 257, 'date': 'Sun, Nov 23, 2025 8:30p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 258, 'round': 258, 'date': 'Sun, Nov 23, 2025 9:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 259, 'round': 259, 'date': 'Sun, Nov 23, 2025 9:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 260, 'round': 260, 'date': 'Mon, Nov 24, 2025 7:00p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 261, 'round': 261, 'date': 'Mon, Nov 24, 2025 10:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 262, 'round': 262, 'date': 'Tue, Nov 25, 2025 7:00p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 263, 'round': 263, 'date': 'Tue, Nov 25, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 264, 'round': 264, 'date': 'Tue, Nov 25, 2025 7:30p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 265, 'round': 265, 'date': 'Tue, Nov 25, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 266, 'round': 266, 'date': 'Tue, Nov 25, 2025 8:00p', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 267, 'round': 267, 'date': 'Tue, Nov 25, 2025 8:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 268, 'round': 268, 'date': 'Tue, Nov 25, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 269, 'round': 269, 'date': 'Tue, Nov 25, 2025 10:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 270, 'round': 270, 'date': 'Tue, Nov 25, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 271, 'round': 271, 'date': 'Wed, Nov 26, 2025 7:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 272, 'round': 272, 'date': 'Wed, Nov 26, 2025 7:30p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 273, 'round': 273, 'date': 'Wed, Nov 26, 2025 8:00p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 274, 'round': 274, 'date': 'Wed, Nov 26, 2025 8:00p', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 275, 'round': 275, 'date': 'Wed, Nov 26, 2025 9:00p', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'San Antonio Spurs', 'result': ''},
        {'match_id': 276, 'round': 276, 'date': 'Wed, Nov 26, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 277, 'round': 277, 'date': 'Fri, Nov 28, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 278, 'round': 278, 'date': 'Fri, Nov 28, 2025 7:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 279, 'round': 279, 'date': 'Fri, Nov 28, 2025 7:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 280, 'round': 280, 'date': 'Fri, Nov 28, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 281, 'round': 281, 'date': 'Fri, Nov 28, 2025 8:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 282, 'round': 282, 'date': 'Fri, Nov 28, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 283, 'round': 283, 'date': 'Fri, Nov 28, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 284, 'round': 284, 'date': 'Fri, Nov 28, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 285, 'round': 285, 'date': 'Fri, Nov 28, 2025 8:30p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 286, 'round': 286, 'date': 'Fri, Nov 28, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 287, 'round': 287, 'date': 'Fri, Nov 28, 2025 10:00p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Houston Rockets', 'result': ''},
        {'match_id': 288, 'round': 288, 'date': 'Sat, Nov 29, 2025 7:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Toronto Raptors', 'result': ''},
        {'match_id': 289, 'round': 289, 'date': 'Sat, Nov 29, 2025 7:30p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 290, 'round': 290, 'date': 'Sat, Nov 29, 2025 8:00p', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 291, 'round': 291, 'date': 'Sat, Nov 29, 2025 10:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 292, 'round': 292, 'date': 'Sat, Nov 29, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 293, 'round': 293, 'date': 'Sun, Nov 30, 2025 3:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 294, 'round': 294, 'date': 'Sun, Nov 30, 2025 6:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Brooklyn Nets', 'result': ''},
        {'match_id': 295, 'round': 295, 'date': 'Sun, Nov 30, 2025 6:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 296, 'round': 296, 'date': 'Sun, Nov 30, 2025 7:00p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 297, 'round': 297, 'date': 'Sun, Nov 30, 2025 7:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 298, 'round': 298, 'date': 'Sun, Nov 30, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 299, 'round': 299, 'date': 'Sun, Nov 30, 2025 8:00p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 300, 'round': 300, 'date': 'Sun, Nov 30, 2025 8:00p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 301, 'round': 301, 'date': 'Sun, Nov 30, 2025 9:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 302, 'round': 302, 'date': 'Sun, Nov 30, 2025 9:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 303, 'round': 303, 'date': 'Sun, Nov 30, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Golden State Warriors', 'result': ''},
        {'match_id': 304, 'round': 304, 'date': 'Mon, Dec 1, 2025 7:00p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 305, 'round': 305, 'date': 'Mon, Dec 1, 2025 9:00p', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'San Antonio Spurs', 'result': ''},
        {'match_id': 306, 'round': 306, 'date': 'Mon, Dec 1, 2025 10:00p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 307, 'round': 307, 'date': 'Tue, Dec 2, 2025 7:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'New York Knicks', 'result': ''},
        {'match_id': 308, 'round': 308, 'date': 'Tue, Dec 2, 2025 7:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 309, 'round': 309, 'date': 'Tue, Dec 2, 2025 7:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 310, 'round': 310, 'date': 'Tue, Dec 2, 2025 8:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 311, 'round': 311, 'date': 'Tue, Dec 2, 2025 8:00p', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 312, 'round': 312, 'date': 'Tue, Dec 2, 2025 8:00p', 'venue': 'Fiserv Forum', 'home_team': 'Milwaukee Bucks', 'away_team': 'Miami Heat', 'result': ''},
        {'match_id': 313, 'round': 313, 'date': 'Tue, Dec 2, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 314, 'round': 314, 'date': 'Tue, Dec 2, 2025 9:00p', 'venue': 'Ball Arena', 'home_team': 'Denver Nuggets', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 315, 'round': 315, 'date': 'Tue, Dec 2, 2025 10:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 316, 'round': 316, 'date': 'Wed, Dec 3, 2025 7:00p', 'venue': 'Kia Center', 'home_team': 'Orlando Magic', 'away_team': 'Toronto Raptors', 'result': ''},
        {'match_id': 317, 'round': 317, 'date': 'Wed, Dec 3, 2025 7:00p', 'venue': 'Little Caesars Arena', 'home_team': 'Detroit Pistons', 'away_team': 'Philadelphia 76ers', 'result': ''},
        {'match_id': 318, 'round': 318, 'date': 'Wed, Dec 3, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 319, 'round': 319, 'date': 'Wed, Dec 3, 2025 8:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 320, 'round': 320, 'date': 'Wed, Dec 3, 2025 8:30p', 'venue': 'Frost Bank Center', 'home_team': 'San Antonio Spurs', 'away_team': 'Utah Jazz', 'result': ''},
        {'match_id': 321, 'round': 321, 'date': 'Wed, Dec 3, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 322, 'round': 322, 'date': 'Thu, Dec 4, 2025 7:00p', 'venue': 'Spectrum Center', 'home_team': 'Charlotte Hornets', 'away_team': 'Brooklyn Nets', 'result': ''},
        {'match_id': 323, 'round': 323, 'date': 'Thu, Dec 4, 2025 7:30p', 'venue': 'TD Garden', 'home_team': 'Boston Celtics', 'away_team': 'Indiana Pacers', 'result': ''},
        {'match_id': 324, 'round': 324, 'date': 'Thu, Dec 4, 2025 7:30p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 325, 'round': 325, 'date': 'Thu, Dec 4, 2025 8:00p', 'venue': 'United Center', 'home_team': 'Chicago Bulls', 'away_team': 'Atlanta Hawks', 'result': ''},
        {'match_id': 326, 'round': 326, 'date': 'Thu, Dec 4, 2025 8:00p', 'venue': 'Smoothie King Center', 'home_team': 'New Orleans Pelicans', 'away_team': 'Minnesota Timberwolves', 'result': ''},
        {'match_id': 327, 'round': 327, 'date': 'Thu, Dec 4, 2025 10:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 328, 'round': 328, 'date': 'Thu, Dec 4, 2025 10:30p', 'venue': 'Intuit Dome', 'home_team': 'Los Angeles Clippers', 'away_team': 'Phoenix Suns', 'result': ''},
        {'match_id': 329, 'round': 329, 'date': 'Fri, Dec 5, 2025 7:00p', 'venue': 'Capital One Arena', 'home_team': 'Washington Wizards', 'away_team': 'Cleveland Cavaliers', 'result': ''},
        {'match_id': 330, 'round': 330, 'date': 'Fri, Dec 5, 2025 7:30p', 'venue': 'Scotiabank Arena', 'home_team': 'Toronto Raptors', 'away_team': 'Orlando Magic', 'result': ''},
        {'match_id': 331, 'round': 331, 'date': 'Fri, Dec 5, 2025 7:30p', 'venue': 'Xfinity Mobile Arena', 'home_team': 'Philadelphia 76ers', 'away_team': 'Detroit Pistons', 'result': ''},
        {'match_id': 332, 'round': 332, 'date': 'Fri, Dec 5, 2025 8:00p', 'venue': 'American Airlines Center', 'home_team': 'Dallas Mavericks', 'away_team': 'Memphis Grizzlies', 'result': ''},
        {'match_id': 333, 'round': 333, 'date': 'Fri, Dec 5, 2025 8:00p', 'venue': 'Kaseya Center', 'home_team': 'Miami Heat', 'away_team': 'Milwaukee Bucks', 'result': ''},
        {'match_id': 334, 'round': 334, 'date': 'Fri, Dec 5, 2025 9:00p', 'venue': 'Delta Center', 'home_team': 'Utah Jazz', 'away_team': 'San Antonio Spurs', 'result': ''},
        {'match_id': 335, 'round': 335, 'date': 'Fri, Dec 5, 2025 10:00p', 'venue': 'Crypto.com Arena', 'home_team': 'Los Angeles Lakers', 'away_team': 'Portland Trail Blazers', 'result': ''},
        {'match_id': 336, 'round': 336, 'date': 'Sat, Dec 6, 2025 7:30p', 'venue': 'State Farm Arena', 'home_team': 'Atlanta Hawks', 'away_team': 'Chicago Bulls', 'result': ''},
        {'match_id': 337, 'round': 337, 'date': 'Sat, Dec 6, 2025 8:00p', 'venue': 'Toyota Center', 'home_team': 'Houston Rockets', 'away_team': 'Los Angeles Lakers', 'result': ''},
        {'match_id': 338, 'round': 338, 'date': 'Sat, Dec 6, 2025 10:00p', 'venue': 'Chase Center', 'home_team': 'Golden State Warriors', 'away_team': 'Denver Nuggets', 'result': ''},
        {'match_id': 339, 'round': 339, 'date': 'Sat, Dec 6, 2025 10:00p', 'venue': 'PHX Arena', 'home_team': 'Phoenix Suns', 'away_team': 'Los Angeles Clippers', 'result': ''},
        {'match_id': 340, 'round': 340, 'date': 'Sun, Dec 7, 2025 3:30p', 'venue': 'Barclays Center', 'home_team': 'Brooklyn Nets', 'away_team': 'Charlotte Hornets', 'result': ''},
        {'match_id': 341, 'round': 341, 'date': 'Sun, Dec 7, 2025 6:00p', 'venue': 'Rocket Arena', 'home_team': 'Cleveland Cavaliers', 'away_team': 'Washington Wizards', 'result': ''},
        {'match_id': 342, 'round': 342, 'date': 'Sun, Dec 7, 2025 6:00p', 'venue': 'Gainbridge Fieldhouse', 'home_team': 'Indiana Pacers', 'away_team': 'Boston Celtics', 'result': ''},
        {'match_id': 343, 'round': 343, 'date': 'Sun, Dec 7, 2025 7:00p', 'venue': 'Madison Square Garden (IV)', 'home_team': 'New York Knicks', 'away_team': 'Toronto Raptors', 'result': ''},
        {'match_id': 344, 'round': 344, 'date': 'Sun, Dec 7, 2025 8:00p', 'venue': 'FedExForum', 'home_team': 'Memphis Grizzlies', 'away_team': 'Dallas Mavericks', 'result': ''},
        {'match_id': 345, 'round': 345, 'date': 'Sun, Dec 7, 2025 8:00p', 'venue': 'Paycom Center', 'home_team': 'Oklahoma City Thunder', 'away_team': 'Sacramento Kings', 'result': ''},
        {'match_id': 346, 'round': 346, 'date': 'Sun, Dec 7, 2025 8:00p', 'venue': 'Target Center', 'home_team': 'Minnesota Timberwolves', 'away_team': 'New Orleans Pelicans', 'result': ''},
        {'match_id': 347, 'round': 347, 'date': 'Sun, Dec 7, 2025 9:00p', 'venue': 'Golden 1 Center', 'home_team': 'Sacramento Kings', 'away_team': 'Oklahoma City Thunder', 'result': ''},
        {'match_id': 348, 'round': 348, 'date': 'Sun, Dec 7, 2025 10:00p', 'venue': 'Moda Center', 'home_team': 'Portland Trail Blazers', 'away_team': 'Utah Jazz', 'result': ''},
    ]
    return nba_schedule
